---
- name: "Copy files for {{app.name}}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest | expanduser }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(raspi_kiosk_user) }}"
    group: "{{ item.group | default(raspi_kiosk_group) }}"
  with_items: "{{ app.files }}"
  become: yes
  when: app.files is defined and app.files is not none

- name: "Copy templates for {{app.name}}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest | expanduser }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(raspi_kiosk_user) }}"
    group: "{{ item.group | default(raspi_kiosk_group) }}"
  with_items: "{{ app.templates }}"
  become: yes
  when: app.templates is defined and app.templates is not none
